In [2]:
import statistics 
import pandas as pd
import numpy as np
from scipy import stats

In [5]:
#tia
beras = 11400
minyak = 12700
ayam = 3400
telur = 21800
popok = 27000
sabun_cuci = 1800
buah_anggur = 3800
roti_tawar = 8500
tissu = 6400
mie_instan = 2200

print("Jumlah Belanjaan tia")
beras_tia = 4
ayam_tia = 2
telur_tia = 3
sabun_cuci_tia = 5
buah_anggur_tia = 4
roti_tawar_tia = 2
mie_instan_tia = 12

jb_tia = (beras_tia * beras) + (ayam_tia * (ayam* 10)) + (telur_tia * telur) + (sabun_cuci_tia * sabun_cuci) + (buah_anggur_tia * buah_anggur) + (roti_tawar_tia * roti_tawar) + (mie_instan_tia * mie_instan)
jb_Diskon_tia = (jb_tia / 100) * 85
print("Maka Jumlah Belanjaan tia Rp. " + str(jb_tia)) 
print("Maka jumlah Belanjaan tia Setelah Mendapatkan Diskon Rp." + str(jb_Diskon_tia))

#hana
beras = 11400
minyak = 12700
ayam = 3400
telur = 21800
popok = 27000
sabun_cuci = 1800
buah_anggur = 3800
roti_tawar = 8500
tissu = 6400
mie_instan = 2200
print("Jumlah Belanjaan hana")
minyak_hana = 2
ayam_hana = 5
telur_hana = 5
sabun_cuci_hana = 3
buah_anggur_hana = 8
roti_tawar_hana = 3
tissu_hana = 2
mie_instan_hana = 20

jb_hana = (minyak_hana * minyak) + (ayam_hana * ayam) + (telur_hana * telur) + (sabun_cuci_hana * sabun_cuci) + (buah_anggur_hana * buah_anggur) + (roti_tawar_hana * roti_tawar) + (tissu_hana * tissu) + (mie_instan_hana * mie_instan)
jb_Diskon_hana = (jb_hana / 100) * 85
print("Maka Jumlah Belanjaan hana Rp. " + str(jb_hana))
print("Maka jumlah Belanjaan hana Setelah Mendapatkan Diskon Rp." + str(jb_Diskon_hana))

#widia
beras = 11400
minyak = 12700
ayam = 3400
telur = 21800
popok = 27000
sabun_cuci = 1800
buah_anggur = 3800
roti_tawar = 8500
tissu = 6400
mie_instan = 2200
print("Jumlah Belanjaan widia")
beras = 1
minyak = 1
telur = 1
buah_anggur = 5
tissu = 3
mie_instan = 16

jb_widia = (beras * beras) + (minyak * (minyak* 1)) + (telur * telur) + (buah_anggur * buah_anggur) + (tissu * tissu) + (mie_instan * mie_instan) + (mie_instan * mie_instan)
print("Maka Jumlah Belanjaan widia Rp." + str(jb_widia))

#romi
minyak = 12700
telur = 21800
sabun_cuci = 1800
mie_instan = 2200
print("Jumlah belanjaan romi")
minyak = 3
telur = 2
sabun_cuci = 800
mie_instan = 8

jb_romi = (minyak * minyak) + (telur * (telur* 3)) + (sabun_cuci * sabun_cuci) + (mie_instan * mie_instan)
print("Maka Jumlah Belanjaan romi Rp." + str(jb_romi))

#samsul
beras = 11400
minyak = 12700
ayam = 3400
telur = 21800
popok = 27000
sabun_cuci = 1800
buah_anggur = 3800
roti_tawar = 8500
tissu = 6400
mie_instan = 2200
print("Jumlah belanjaan samsul")
ayam = 5
popok = 5
sabun_cuci = 4
buah_anggur = 3
roti_tawar = 5
mie_instan = 6



print("==SOAL 3==")

maxz = [284475]
print("maka jumlah belanjaan paling besar setelah diskon adalah dimas rp. " + str(maxz))

Jumlah Belanjaan tia
Maka Jumlah Belanjaan tia Rp. 246600
Maka jumlah Belanjaan tia Setelah Mendapatkan Diskon Rp.209610.0
Jumlah Belanjaan hana
Maka Jumlah Belanjaan hana Rp. 269500
Maka jumlah Belanjaan hana Setelah Mendapatkan Diskon Rp.229075.0
Jumlah Belanjaan widia
Maka Jumlah Belanjaan widia Rp.549
Jumlah belanjaan romi
Maka Jumlah Belanjaan romi Rp.640085
Jumlah belanjaan samsul
==SOAL 3==
maka jumlah belanjaan paling besar setelah diskon adalah dimas rp. [284475]